version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vectra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    command: poetry run python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "${SERVER_PORT}:8000"
    restart: always
    environment:
      - DB_NAME=vectra
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  data: